{
 "title": "Logs / Unifi / Flows / Overview",
 "tags": [
  "Unifi",
  "Loki"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   { "name": "job", "label": "Job", "query": "unifi-exporter" },
   { "name": "service_name", "label": "Service Name", "query": "firewall" },
   {
    "name": "smooth",
    "label": "Smooth",
    "query": "1s,5s,10s,15s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Flow Rate",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"$job\", service_name=\"$service_name\"} [$__auto]))",
     "legendFormat": "Total Flows"
    }
   ]
  },
  {
   "title": "Top Source IPs",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by(source_ip) (count_over_time({job=\"$job\", service_name=\"$service_name\"} | json [$__range])))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Top Destination IPs",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(5, sum by(destination_ip) (count_over_time({job=\"$job\", service_name=\"$service_name\"} | json [$__auto])))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Total Flows",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"$job\", service_name=\"$service_name\"} [$__auto]))"
    }
   ]
  },
  {
   "title": "Permitted Flows",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"$job\", service_name=\"$service_name\", action=\"permit\"} [$__auto]))"
    }
   ]
  },
  {
   "title": "Pre-Routing Port Forwards",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"$job\", service_name=\"$service_name\", portforward_stage=\"PREROUTING\"} [$__auto]))"
    }
   ]
  },
  {
   "title": "DNAT Flows",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"$job\", service_name=\"$service_name\", portforward_type=\"DNAT\"} [$__auto]))"
    }
   ]
  },
  {
   "title": "Top Destination Ports",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by(destination_port) (count_over_time({job=\"$job\", service_name=\"$service_name\"} | json [$__range])))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Protocols",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(protocol) (count_over_time({job=\"$job\", service_name=\"$service_name\"} [$__range]))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Denied Flows",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"$job\", service_name=\"$service_name\", action=\"deny\"} [$__auto]))"
    }
   ]
  },
  {
   "title": "Post-Routing Port Forwards",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"$job\", service_name=\"$service_name\", portforward_stage=\"POSTROUTING\"} [$__auto]))"
    }
   ]
  },
  {
   "title": "MASQUERADE Flows",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"$job\", service_name=\"$service_name\", portforward_type=\"MASQUERADE\"} [$__auto]))"
    }
   ]
  },
  {
   "title": "Source Zones",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(source_zone) (count_over_time({job=\"$job\", service_name=\"$service_name\"} [$__auto]))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Destination Zones",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(5, sum by(destination_zone) (count_over_time({job=\"$job\", service_name=\"$service_name\"} [$__auto])))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Source Interfaces",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(source_interface) (count_over_time({job=\"$job\", service_name=\"$service_name\"} [$__auto]))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Destination Interfaces",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(destination_interface) (count_over_time({job=\"$job\", service_name=\"$service_name\"} [$__auto]))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "GeoIP  Coordinates",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"$job\", service_name=\"$service_name\", source_country=~\".+\"} | json latitude=\"source_latitude\", longitude=\"source_longitude\""
    },
    {
     "direction": "backward",
     "expr": "{job=\"$job\", service_name=\"$service_name\", destination_country=~\".+\"} | json latitude=\"destination_latitude\", longitude=\"destination_longitude\""
    }
   ]
  },
  {
   "title": "Top Source Countries",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(5, sum by(source_country) (count_over_time({job=\"$job\", service_name=\"$service_name\", source_country=~\".+\"} [$__range])))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Top Destination Countries",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(5, sum by(destination_country) (count_over_time({job=\"$job\", service_name=\"$service_name\", destination_country=~\".+\"} [$__range])))",
     "legendFormat": "{{auto}}"
    }
   ]
  }
 ]
}