{
 "title": "Logs / Unifi / Services",
 "tags": [
  "Loki",
  "Unifi"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   {
    "name": "smooth",
    "label": "Smooth",
    "query": "1s,5s,10s,15s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job",
    "label": "Job",
    "query": {}
   },
   { "name": "type", "label": "Type", "query": "flow.*|portforward.*" },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {}
   },
   {
    "name": "service",
    "label": "Service",
    "query": {}
   },
   {
    "name": "facility",
    "label": "Facility",
    "query": {}
   },
   {
    "name": "level",
    "label": "Level",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Total Log Volume",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"$job\", type!~\"$type\", hostname=~\"$hostname\", service_name=~\"$service\", facility=~\"$facility\", level=~\"$level\"} [$__auto]))",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Log Volume by Level",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(level) (count_over_time({job=\"$job\", type!~\"$type\", hostname=~\"$hostname\", service_name=~\"$service\", facility=~\"$facility\", level=~\"$level\"} [$__auto]))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Log Volume by Level",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(level) (count_over_time({job=\"$job\", type!~\"$type\", hostname=~\"$hostname\", service_name=~\"$service\", facility=~\"$facility\", level=~\"$level\"} [$__auto]))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Log Volume by Facility",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(facility) (count_over_time({job=\"$job\", type!~\"$type\", hostname=~\"$hostname\", service_name=~\"$service\", facility=~\"$facility\", level=~\"$level\"} [$__auto]))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Log Volume by Facility",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(facility) (count_over_time({job=\"$job\", type!~\"$type\", hostname=~\"$hostname\", service_name=~\"$service\", facility=~\"$facility\", level=~\"$level\"} [$__auto]))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Log Volume by Service (Top)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(1, sum by(service_name) (count_over_time({job=\"$job\", type!~\"$type\", hostname=~\"$hostname\", service_name=~\"$service\", facility=~\"$facility\", level=~\"$level\"} [$__auto])))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Log Volume by Service",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(service_name) (count_over_time({job=\"$job\", type!~\"$type\", hostname=~\"$hostname\", service_name=~\"$service\", facility=~\"$facility\", level=~\"$level\"} [$__auto]))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Log Volume by Hostname",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(hostname) (count_over_time({job=\"$job\", type!~\"$type\", hostname=~\"$hostname\", service_name=~\"$service\", facility=~\"$facility\", level=~\"$level\"} [$__auto]))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Log Volume by Hostname",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(hostname) (count_over_time({job=\"$job\", type!~\"$type\", hostname=~\"$hostname\", service_name=~\"$service\", facility=~\"$facility\", level=~\"$level\"} [$__auto]))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"$job\", type!~\"$type\", hostname=~\"$hostname\", service_name=~\"$service\", facility=~\"$facility\", level=~\"$level\"}"
    }
   ]
  }
 ]
}