{
 "title": "Logs / Unifi / Flows / Investigate",
 "tags": [
  "Loki",
  "Unifi"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   {
    "name": "smooth",
    "label": "Smooth",
    "query": "1s,5s,10s,15s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "job", "label": "Job", "query": "unifi-exporter" },
   { "name": "service_name", "label": "Service Name", "query": "firewall" },
   {
    "name": "action",
    "label": "Action",
    "query": {}
   },
   {
    "name": "protocol",
    "label": "Protocol",
    "query": {}
   },
   {
    "name": "source_zone",
    "label": "Source Zone",
    "query": {}
   },
   {
    "name": "source_interface",
    "label": "Source Interface",
    "query": {}
   },
   { "name": "source_ip", "label": "Source IP", "query": ".*" },
   { "name": "source_port", "label": "Source Port", "query": ".*" },
   {
    "name": "destination_zone",
    "label": "Destination Zone",
    "query": {}
   },
   {
    "name": "destination_interface",
    "label": "Destination Interface",
    "query": {}
   },
   { "name": "destination_ip", "label": "Destination IP", "query": ".*" },
   { "name": "destination_port", "label": "Destination Port", "query": ".*" }
  ]
 },
 "panels": [
  { "title": "Insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Flow Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"$job\", service_name=\"$service_name\", action=~\"$action\", protocol=~\"$protocol\", source_zone=~\"$source_zone\", source_interface=~\"$source_interface\", destination_zone=~\"$destination_zone\", destination_interface=~\"$destination_interface\"} | json source_ip=\"source_ip\", source_port=\"source_port\", destination_ip=\"destination_ip\", destination_port=\"destination_port\" | source_ip =~ `^$source_ip$` | source_port =~ `^$source_port$` | destination_ip =~ `^$destination_ip$` | destination_port =~ `^$destination_port$` [$__auto]))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 23, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"$job\", service_name=\"$service_name\", action=~\"$action\", protocol=~\"$protocol\", source_zone=~\"$source_zone\", source_interface=~\"$source_interface\", destination_zone=~\"$destination_zone\", destination_interface=~\"$destination_interface\", source_country=~\".+\"} | json source_ip=\"source_ip\", source_port=\"source_port\", destination_ip=\"destination_ip\", destination_port=\"destination_port\", latitude=\"source_latitude\", longitude=\"source_longitude\" | source_ip =~ `^$source_ip$` | source_port =~ `^$source_port$` | destination_ip =~ `^$destination_ip$` | destination_port =~ `^$destination_port$` | latitude =~ `.+` | longitude =~ `.+`",
     "legendFormat": "{{auto}}"
    },
    {
     "direction": "backward",
     "expr": "{job=\"$job\", service_name=\"$service_name\", action=~\"$action\", protocol=~\"$protocol\", source_zone=~\"$source_zone\", source_interface=~\"$source_interface\", destination_zone=~\"$destination_zone\", destination_interface=~\"$destination_interface\", destination_country=~\".+\"} | json source_ip=\"source_ip\", source_port=\"source_port\", destination_ip=\"destination_ip\", destination_port=\"destination_port\", latitude=\"destination_latitude\", longitude=\"destination_longitude\" | source_ip =~ `^$source_ip$` | source_port =~ `^$source_port$` | destination_ip =~ `^$destination_ip$` | destination_port =~ `^$destination_port$` | latitude =~ `.+` | longitude =~ `.+`",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Total Flows",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"$job\", service_name=\"$service_name\", action=~\"$action\", protocol=~\"$protocol\", source_zone=~\"$source_zone\", source_interface=~\"$source_interface\", destination_zone=~\"$destination_zone\", destination_interface=~\"$destination_interface\"} | json source_ip=\"source_ip\", source_port=\"source_port\", destination_ip=\"destination_ip\", destination_port=\"destination_port\" | source_ip =~ `^$source_ip$` | source_port =~ `^$source_port$` | destination_ip =~ `^$destination_ip$` | destination_port =~ `^$destination_port$` [$__auto]))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Permitted Flows",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"$job\", service_name=\"$service_name\", action=\"permit\", protocol=~\"$protocol\", source_zone=~\"$source_zone\", source_interface=~\"$source_interface\", destination_zone=~\"$destination_zone\", destination_interface=~\"$destination_interface\"} | json source_ip=\"source_ip\", source_port=\"source_port\", destination_ip=\"destination_ip\", destination_port=\"destination_port\" | source_ip =~ `^$source_ip$` | source_port =~ `^$source_port$` | destination_ip =~ `^$destination_ip$` | destination_port =~ `^$destination_port$` [$__auto]))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Denied Flows",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"$job\", service_name=\"$service_name\", action=\"deny\", protocol=~\"$protocol\", source_zone=~\"$source_zone\", source_interface=~\"$source_interface\", destination_zone=~\"$destination_zone\", destination_interface=~\"$destination_interface\"} | json source_ip=\"source_ip\", source_port=\"source_port\", destination_ip=\"destination_ip\", destination_port=\"destination_port\" | source_ip =~ `^$source_ip$` | source_port =~ `^$source_port$` | destination_ip =~ `^$destination_ip$` | destination_port =~ `^$destination_port$` [$__auto]))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Source Zones",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 3, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(source_zone) (count_over_time({job=\"$job\", service_name=\"$service_name\", action=~\"$action\", protocol=~\"$protocol\", source_zone=~\"$source_zone\", source_interface=~\"$source_interface\", destination_zone=~\"$destination_zone\", destination_interface=~\"$destination_interface\"} | json source_ip=\"source_ip\", source_port=\"source_port\", destination_ip=\"destination_ip\", destination_port=\"destination_port\" | source_ip =~ `^$source_ip$` | source_port =~ `^$source_port$` | destination_ip =~ `^$destination_ip$` | destination_port =~ `^$destination_port$` [$__auto]))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Source Interfaces",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 3, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(source_interface) (count_over_time({job=\"$job\", service_name=\"$service_name\", action=~\"$action\", protocol=~\"$protocol\", source_zone=~\"$source_zone\", source_interface=~\"$source_interface\", destination_zone=~\"$destination_zone\", destination_interface=~\"$destination_interface\"} | json source_ip=\"source_ip\", source_port=\"source_port\", destination_ip=\"destination_ip\", destination_port=\"destination_port\" | source_ip =~ `^$source_ip$` | source_port =~ `^$source_port$` | destination_ip =~ `^$destination_ip$` | destination_port =~ `^$destination_port$` [$__auto]))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Destination Zones",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 3, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(destination_zone) (count_over_time({job=\"$job\", service_name=\"$service_name\", action=~\"$action\", protocol=~\"$protocol\", source_zone=~\"$source_zone\", source_interface=~\"$source_interface\", destination_zone=~\"$destination_zone\", destination_interface=~\"$destination_interface\"} | json source_ip=\"source_ip\", source_port=\"source_port\", destination_ip=\"destination_ip\", destination_port=\"destination_port\" | source_ip =~ `^$source_ip$` | source_port =~ `^$source_port$` | destination_ip =~ `^$destination_ip$` | destination_port =~ `^$destination_port$` [$__auto]))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Destination Interfaces",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(destination_interface) (count_over_time({job=\"$job\", service_name=\"$service_name\", action=~\"$action\", protocol=~\"$protocol\", source_zone=~\"$source_zone\", source_interface=~\"$source_interface\", destination_zone=~\"$destination_zone\", destination_interface=~\"$destination_interface\"} | json source_ip=\"source_ip\", source_port=\"source_port\", destination_ip=\"destination_ip\", destination_port=\"destination_port\" | source_ip =~ `^$source_ip$` | source_port =~ `^$source_port$` | destination_ip =~ `^$destination_ip$` | destination_port =~ `^$destination_port$` [$__auto]))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Protocols",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(protocol) (count_over_time({job=\"$job\", service_name=\"$service_name\", action=~\"$action\", protocol=~\"$protocol\", source_zone=~\"$source_zone\", source_interface=~\"$source_interface\", destination_zone=~\"$destination_zone\", destination_interface=~\"$destination_interface\"} | json source_ip=\"source_ip\", source_port=\"source_port\", destination_ip=\"destination_ip\", destination_port=\"destination_port\" | source_ip =~ `^$source_ip$` | source_port =~ `^$source_port$` | destination_ip =~ `^$destination_ip$` | destination_port =~ `^$destination_port$` [$__auto]))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "type": "logs",
   "gridPos": { "h": 33, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"$job\", service_name=\"$service_name\", action=~\"$action\", protocol=~\"$protocol\", source_zone=~\"$source_zone\", source_interface=~\"$source_interface\", destination_zone=~\"$destination_zone\", destination_interface=~\"$destination_interface\"} | json | source_ip =~ `^$source_ip$` | source_port =~ `^$source_port$` | destination_ip =~ `^$destination_ip$` | destination_port =~ `^$destination_port$`",
     "legendFormat": "{{auto}}"
    }
   ]
  }
 ]
}