apiVersion: v2
name: unifi-exporter
description: A Helm chart for deploying the Unifi Exporter to Kubernetes.
type: application
version: 1.0.2
appVersion: "v1.0.2"
dependencies:
  - name: loki
    alias: loki
    repository: https://grafana.github.io/helm-charts
    version: 6.31.0
    condition: loki.enabled
  - name: grafana
    alias: grafana
    repository: https://grafana.github.io/helm-charts
    version: 9.2.10
    condition: grafana.enabled
