name: Helm Lint
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '.gitignore'
      - '.github/workflows/helmlint.yaml'
      - '.github/workflows/release.yaml'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.12.0

      - name: Lint Helm Charts
        run: |
          helm lint charts/unifi-exporter