name: Helm Lint
on:
  pull_request:
    paths-ignore:
      - '**/README.md'
      - '.gitignore'
      - '.github/workflows/lint.yaml'
      - '.github/workflows/release.yaml'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Lint Helm Charts
        run: |
          helm lint charts/unifi-exporter